vid = videoinput('winvideo', 1, 'YUY2_1280x720');
src = getselectedsource(vid);
vid.FramesPerTrigger = 1;
vid.ReturnedColorspace = 'rgb';
src.BacklightCompensation = 'off';
src.ExposureMode = 'manual';
src.FocusMode = 'manual';
src.WhiteBalanceMode = 'manual';
triggerconfig(vid, 'manual');
vid.ROIPosition = [338 0 636 433];
src.Exposure = -6;
src.Brightness = 133;
start(vid);
pause(1);
trigger(vid);
e = getdata(vid);
save('r3.mat', 'e');
src.Exposure = -8;
start(vid);
pause(1);
trigger(vid);
i = getdata(vid);
save('i3.mat', 'i');